language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

env:
  global:
    secure: "lA8kB2x48k7Y4fkdIX5ecOtD/DJgJWCTI6rSkSjshNYwaTTBN6rK4qeRGWZXueYW/P28oJ3A5wdb+JsK2OMlLM0iTnwoX3SwCuD7SI0QpzWn6xcX1+vQgOTMq3fsI7jIbVjjLXxi2vx7oTtXlH6icAr1rqB5lW45AYjTdORkXws="

before_install:
  - sudo apt-get install -qq gfortran pandoc
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - conda create --yes -n condaenv python=$TRAVIS_PYTHON_VERSION
  - conda install --yes -n condaenv pip
  - source activate condaenv
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - conda install --yes python=$TRAVIS_PYTHON_VERSION nose pytest flake8 sphinx ipython-notebook
  - conda install --yes python=$TRAVIS_PYTHON_VERSION -c obspy obspy
  - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then pip install --use-mirrors sphinx-readable-theme runipy; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then conda install --yes basemap; fi
  - pip install coveralls

install:
  - pip install --no-deps -v -e .

script:
  - coverage run --source=src/pyadjoint -m pyadjoint.tests
  - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then cd $TRAVIS_BUILD_DIR/doc; make html ; fi

after_success:
  - cd $TRAVIS_BUILD_DIR; coveralls
  - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then bash $TRAVIS_BUILD_DIR/.travis-update-gh-pages.sh ; fi
